import type { Metadata } from 'next'
import './globals.css'
import GlobalProvider from '@/config/GlobalProvider'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html className="h-full" lang="en">
         <body className={cn('relative h-full font-sans antialiased')}>
            <GlobalProvider>
               <main className="flex flex-col min-h-screen">
                  <div className="flex-grow flex-1">{children}</div>
               </main>
            </GlobalProvider>
         </body>
      </html>
   )
}
